#!/usr/bin/env node
var jsiGame = require('jsi-gamelib');
var prompt = require('prompt');
var gameMap = require('./game.json');
var getLocation = require('./location');
var getMessage = require('./message');

getLocation.currentRoom('A');

//prompt
//console.log(require('jsi-gamelib').map(require('./' + process.argv[2])));
