#!/usr/bin/env node

var readline = require('readline');

var rl = readline.createInterface({
  input : process.stdin,
  output : process.stdout
});


rl.question("Please enter a positive integer : ", function(answerOne){
    var firstTerm = parseInt(answerOne);
    function sumOf(term1, term2){
      var answer = (term1 + term2); 
      return answer;
    }
    if(typeof firstTerm !== 'number'){
      console.log("That is not an integer.");
      rl.close();
    } else {
      console.log(typeof firstTerm);
      console.log('next question');
      rl.question("Please enter another postive integer : ", function(answerTwo){
        var secondTerm = parseInt(answerTwo);
        if(typeof firstTerm !== 'number'){
          console.log("That is not an integer.");
          rl.close();
        } else {
          console.log(sumOf(firstTerm, secondTerm) + ' is the sum of those integers.');
          rl.close();
        }
      });
    }
      

});
