#!/usr/bin/env node  
var shell = require('commander');
var inCommon = require('./inCommon');
var returnFiles = require('./readfiles');


shell
  .version('0.0.3')
  .usage('[options] <file1> <file2>')
  .option('-n, --number','Report just the number of words')
  .option('-v, --verbose', 'Be more verbose, report timing information')
  .parse(process.argv);

var arrr = shell.args;
if(shell.number) console.log('n words in common.');
if(shell.verbose) console.log('[time] read the files: ms', '[time] word comparison: ms');
returnFiles.readFiles(arrr[0], arrr[1]);
//inCommon.toCompare(arrr[0], arrr[1]);


 /*
function countWords(str) {
  return str.split(/\s+/).length;
}
fs.readFile('./textfileone.txt', { encoding: 'utf8' }, function (err, content){
  console.log(countWords(content));
});
*/




